name: marp-to-pages

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed
jobs:
  build:
    permissions:
      contents: read
      deployments: write
      statuses: write
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy images
        run: |
            mkdir build
            cp -R img build/
            cp -R exercices build/
            cp -R videos build/

      - name: Marp Build (Html)
        uses: docker://marpteam/marp-cli:v3.4.0
        with:
          args: slide-deck.md -o build/index.html --html --bespoke.progress --template bespoke
        env:
          MARP_USER: root:root
          
      - name: Marp Build (pdf)
        uses: docker://marpteam/marp-cli:v3.4.0
        with:
          args: slide-deck.md -o build/PrezVim.pdf --pdf --bespoke.progress --template bespoke --allow-local-files
        env:
          MARP_USER: root:root

      - name: Publish
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: prezvim
          directory: build
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
